### ISSUE TITLE
You've left cloudbees 😉  (stale README)

### ISSUE THREAD

**Issue by timja** [oleg-nenashev/oleg-nenashev#1]
@oleg-nenashev README could do with an update 😉

**Comment by oleg-nenashev** [comment]
Thanks for the reminder. Sometimes I forget about it 😂

**Comment by oleg-nenashev** [comment]
Thanks! Fixed in https://github.com/oleg-nenashev/oleg-nenashev/commit/3445f43489cc6fbd21c61e136efca3ad72cf33f1
